query Car($documentId: ID!, $status: PublicationStatus) {
  car(documentId: $documentId, status: $status) {
    model
    name
    image {
      url
    }
    documentId
    year
    owners {
      fullname
      documentId
    }
  }
}
